# Web Scraping Assignment 2 (Using Selenium)

# By Olayemi Morrison

# Project: Batch DS2306

#### Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

#### This task will be done in following steps:
1. First get the webpage https://www.naukri.com/
2. Enter “Data Analyst” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [2]:
# Import all required libraries

import selenium                                  #library that is used to work with selenium

from selenium import webdriver                   #importing webdriver module from selenium to open automated chrome window

import pandas as pd                              #to create DataFrame

from selenium.webdriver.common.by import By      #importing inbuilt class By 

import warnings                                  #to ignore any sort of warning

warnings.filterwarnings("ignore")

import time                                      #use to stop search engine for few seconds


from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.chrome.service import Service

import undetected_chromedriver as uc
driver = uc.Chrome()

In [3]:
#Opening the naukri page on automated chrome driver
driver.get("https://www.naukri.com")

In [4]:
# entering designation

designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Analyst')

In [5]:
# entering location
location=driver.find_element(By.XPATH, "/html/body/div[1]/div[7]/div/div/div[5]/div/div/div/div[1]/div/input")
location.send_keys('Bangalore')

In [10]:
# click the search button
search=driver.find_element(By.CLASS_NAME, "qsbSubmit")
search.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".qsbSubmit"}
  (Session info: chrome=115.0.5790.99); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
Backtrace:
	GetHandleVerifier [0x011AA813+48355]
	(No symbol) [0x0113C4B1]
	(No symbol) [0x01045358]
	(No symbol) [0x010709A5]
	(No symbol) [0x01070B3B]
	(No symbol) [0x0109E232]
	(No symbol) [0x0108A784]
	(No symbol) [0x0109C922]
	(No symbol) [0x0108A536]
	(No symbol) [0x010682DC]
	(No symbol) [0x010693DD]
	GetHandleVerifier [0x0140AABD+2539405]
	GetHandleVerifier [0x0144A78F+2800735]
	GetHandleVerifier [0x0144456C+2775612]
	GetHandleVerifier [0x012351E0+616112]
	(No symbol) [0x01145F8C]
	(No symbol) [0x01142328]
	(No symbol) [0x0114240B]
	(No symbol) [0x01134FF7]
	BaseThreadInitThunk [0x76897D59+25]
	RtlInitializeExceptionChain [0x7795B79B+107]
	RtlClearBits [0x7795B71F+191]

In [7]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

# scraping job title from web page
title_tags=driver.find_elements(By.XPATH, "//a[@class='title ellipsis']")
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)
    


# scraping job location from web page
location_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft locWdth']")
for i in location_tags[0:10]:
    location=i.text
    job_location.append(location)



# scraping company name from web page
company_tags=driver.find_elements(By.XPATH, "//a[@class='subTitle ellipsis fleft']")
for i in company_tags[0:10]:
    company=i.text
    company_name.append(company)
    


# scraping experience from web page
experience_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft expwdth']")
for i in experience_tags[0:10]:
    experience=i.text
    experience_required.append(experience)

In [8]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

10 10 10 10

In [9]:
import pandas as pd
df=pd.DataFrame({'Title':job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df

,Title,Location,Company_name,Experience
0,Data Analyst,Bangalore/Bengaluru,Eastvantage,4-6 Yrs
1,Data Analyst,"Bangalore/ Bengaluru, Karnataka, Gurgaon/ Guru...",Delhivery,1-3 Yrs
2,HCL hiring For GCP Data Analyst,"Bangalore/ Bengaluru, Karnataka, Hyderabad/ Se...",HCLTech,5-10 Yrs
3,Data Analyst,Bangalore/Bengaluru,Everest Vacuum,2-5 Yrs
4,Data Analyst,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Boomi Software,1-5 Yrs
5,Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune",Synechron,5-8 Yrs
6,Data Analyst,"Bangalore/Bengaluru, Hyderabad/Secunderabad, Pune",Synchron Infotech,5-8 Yrs
7,Data Analyst I,Bangalore/Bengaluru,Cerner,5-10 Yrs
8,Data Analyst,Bangalore/Bengaluru,Persolkelly India,0-2 Yrs
9,Data Analyst,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Truthfools,3-8 Yrs

#### Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.
#### This task will be done in following steps:
1. First get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results youget.
5. Finally create a dataframe of the scraped data.

In [17]:
#Opening the naukri page on automated chrome driver
driver.get("https://www.naukri.com")

In [18]:
# entering designation

designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

In [19]:
#entering the location

location=driver.find_element(By.XPATH, "/html/body/div[1]/div[6]/div/div/div[5]/div/div/div/div[1]/div/input")
location.send_keys('Bangalore')

In [20]:
#Click the search button
search=driver.find_element(By.CLASS_NAME, "qsbSubmit")
search.click()

In [21]:
job_title2=[]
job_location2=[]
company_name2=[]
experience_required2=[]

# scraping job title from web page
title_tags=driver.find_elements(By.XPATH, "//a[@class='title ellipsis']")
for i in title_tags[0:10]:
    title=i.text
    job_title2.append(title)
    


# scraping job location from web page
location_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft locWdth']")
for i in location_tags[0:10]:
    location=i.text
    job_location2.append(location)



# scraping company name from web page
company_tags=driver.find_elements(By.XPATH, "//a[@class='subTitle ellipsis fleft']")
for i in company_tags[0:10]:
    company=i.text
    company_name2.append(company)
    


# scraping experience from web page
experience_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft expwdth']")
for i in experience_tags[0:10]:
    experience=i.text
    experience_required2.append(experience)

In [22]:
print(len(job_title2),len(job_location2),len(company_name2),len(experience_required2))

10 10 10 10

In [23]:
import pandas as pd
df=pd.DataFrame({'Title':job_title2,'Location':job_location2,'Company_name':company_name2,'Experience':experience_required2})
df

,Title,Location,Company_name,Experience
0,Analystics & Modeling Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture,6-8 Yrs
1,Data Science Specialist,"Bangalore/Bengaluru, Kolkata, Mumbai, Hyderaba...",Accenture,2-4 Yrs
2,Data Scientist,"Bangalore/Bengaluru, Mumbai (All Areas)",PwC,3-6 Yrs
3,Data Scientist,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",Tredence,2-4 Yrs
4,Data Scientist,"Bangalore/Bengaluru, Kolkata, Mumbai, New Delh...",IBS Software Services,5-8 Yrs
5,ACN - Applied Intelligence - Finance - Data Sc...,"Bangalore/Bengaluru, Hyderabad/Secunderabad, P...",Accenture,2-7 Yrs
6,Senior Data Scientist,"Bangalore/Bengaluru, Mumbai",Fractal Analytics,5-10 Yrs
7,Data Scientist,"Hybrid - Bangalore/ Bengaluru, Karnataka, Noid...",HCLTech,7-12 Yrs
8,Data Scientist with Retail Domain,"Bangalore/Bengaluru, Kolkata, Mumbai, Nagpur, ...",TRH Consultancy Services,4-9 Yrs
9,Data Scientist,"Bangalore/Bengaluru, Noida, Kolkata, Mumbai, H...",TRH Consultancy Services,5-10 Yrs

#### Q3: In this question you have to scrape data using the filters available on the webpage as shown below

You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company name, experience required.
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

The task will be done as shown in the below steps:
1. first get thewebpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field.
3. Then click the searchbutton.
4. Then apply the location filter and salary filter by checking the respective boxes
5. Then scrape the data for the first 10 jobs results youget.
6. Finally create a dataframe of the scraped data.

In [24]:
#Opening the naukri page on automated chrome driver
driver.get("https://www.naukri.com")

In [25]:
# entering designation and loacation

designation=driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Scientist')

In [26]:
#clicking the search button

search=driver.find_element(By.CLASS_NAME, "qsbSubmit")
search.click()

In [27]:
# click the location filter
location=driver.find_element(By.XPATH, "/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[5]/div[2]/div[2]/label/p/span[1]")
location.click()

In [28]:
# click the salary filter
salary=driver.find_element(By.XPATH, "/html/body/div[1]/div[4]/div/div/section[1]/div[2]/div[6]/div[2]/div[2]/label/p/span[1]")
salary.click()

In [29]:
job_title3=[]
job_location3=[]
company_name3=[]
experience_required3=[]

# scraping job title from web page
title_tags=driver.find_elements(By.XPATH, "//a[@class='title ellipsis']")
for i in title_tags[0:10]:
    title=i.text
    job_title3.append(title)
    


# scraping job location from web page
location_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft locWdth']")
for i in location_tags[0:10]:
    location=i.text
    job_location3.append(location)



# scraping company name from web page
company_tags=driver.find_elements(By.XPATH, "//a[@class='subTitle ellipsis fleft']")
for i in company_tags[0:10]:
    company=i.text
    company_name3.append(company)
    


# scraping experience from web page
experience_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft expwdth']")
for i in experience_tags[0:10]:
    experience=i.text
    experience_required3.append(experience)

In [30]:
print(len(job_title3),len(job_location3),len(company_name3),len(experience_required3))

10 10 10 10

In [31]:
import pandas as pd
df=pd.DataFrame({'Title':job_title3,'Location':job_location3,'Company_name':company_name3,'Experience':experience_required3})
df

,Title,Location,Company_name,Experience
0,Junior Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,0-2 Yrs
1,Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru",Blackbuck,3-7 Yrs
2,Data Scientist/ Senior Data Scientist/ Manager...,"Noida, Kolkata, Mumbai, Chandigarh, Hyderabad/...",Dreambig It Solutions India,1-6 Yrs
3,Data Scientist,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Analytos,2-4 Yrs
4,Data Scientist,Noida,Times Internet,3-8 Yrs
5,Python and ML Trainer,"Hyderabad/Secunderabad, New Delhi, Pune, Gurga...",Thescholar,3-8 Yrs
6,Hiring For Data Scientist,Remote,Infogain,4-9 Yrs
7,Junior Data Scientist,"Gurgaon/Gurugram, United States (USA), Bulgaria",Adidas,1-6 Yrs
8,Associate Data Scientist - ML & NLP,Gurgaon/Gurugram,Gartner,2-4 Yrs
9,Data Scientist,Noida,Gujarat Fluorochemicals,1-2 Yrs

#### Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
1. Brand
2. Product Description
3. Price

#### The attributes which you have to scrape is ticked marked in the below image.
To scrape the data you have to go through following steps:
1. Go to Flipkart webpage by url : https://www.flipkart.com/
2. Enter “sunglasses” in the search field where “search for products, brands and more” is written and
click the search icon
3. After that you will reach to the page having a lot of sunglasses. From this page you can scrap the
required data as usual.
4. After scraping data from the first page, go to the “Next” Button at the bottom other page , then
click on it.
5. Now scrape data from this page as usual
6. Repeat this until you get data for 100 sunglasses.

In [34]:
#Opening the flipkart page on automated chrome driver
driver.get("https://www.flipkart.com/")

In [36]:
# entering sunglasses in the search field

search=driver.find_element(By.CLASS_NAME,"_3704LK")
search.send_keys('sunglasses')

In [38]:
#clicking the search button
search_btn=driver.find_element(By.CLASS_NAME, "L0Z3Pu")
search_btn.click()

In [39]:
# scraping sunglasses data for brand, product price
brand=[]
product_desc=[]
price=[]

start=0
end=3       #to scrape data from the first 3 pages
for page in range(start,end):
    brand_name=driver.find_elements(By.XPATH, '//div[@class="_2WkVRV"]')
    for i in brand_name:
        brand.append(i.text)
        
    description=driver.find_elements(By.XPATH, '//a[@class="IRpwTa"]')
    for i in description:
        product_desc.append(i.text)
    
    prc=driver.find_elements(By.XPATH, '//div[@class="_30jeq3"]')
    for i in prc:
        price.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(10)

In [40]:
print(len(brand),len(product_desc),len(price))

120 111 120

In [41]:
import pandas as pd
df=pd.DataFrame({'Brand':brand[0:100],'Product_Description':product_desc[0:100],'Price':price[0:100]})
df

             Brand                                Product_Description   Price
0   ROZZETTA CRAFT         UV Protection Retro Square Sunglasses (54)    ₹490
1           OAKLEY                         HOLBROOK Wayfarer Sunglass  ₹4,981
2             SRPM             UV Protection Wayfarer Sunglasses (50)    ₹194
3         Fastrack   UV Protection Rectangular Sunglasses (Free Size)    ₹675
4        Elligator  UV Protection Cat-eye, Retro Square, Oval, Rou...    ₹168
..             ...                                                ...     ...
95      Cool enter                UV Protection Round Sunglasses (50)    ₹183
96   VINCENT CHASE  UV Protection, Riding Glasses, Polarized, Grad...    ₹949
97       ROYAL SON  Gradient, UV Protection Wayfarer Sunglasses (F...    ₹379
98          RELIZA         UV Protection Retro Square Sunglasses (51)    ₹849
99         ROADWAY  Mirrored, Night Vision, UV Protection Wayfarer...    ₹256

[100 rows x 3 columns]

#### Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link:
https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market

As shown in the above page you have to scrape the tick marked attributes. These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100reviews.

In [44]:
#Opening the flipkart page on automated chrome driver
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market")

In [45]:
# scraping iphone data for rating, review summary & full review
rating=[]
review_summary=[]
full_review=[]

start=0
end=10     #to scrape data from the first 10 pages
for page in range(start,end):
    rating_tag=driver.find_elements(By.XPATH, '//div[@class="_3LWZlK _1BLPMq"]')
    for i in rating_tag:
        rating.append(i.text)
        
    review_tag=driver.find_elements(By.XPATH, '//p[@class="_2-N8zT"]')
    for i in review_tag:
        review_summary.append(i.text)
    
    f_review=driver.find_elements(By.XPATH, '//div[@class="t-ZTKy"]')
    for i in f_review:
        full_review.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(5)

In [46]:
print(len(rating),len(review_summary),len(full_review))

100 100 100

In [47]:
import pandas as pd
df=pd.DataFrame({'Rating':rating,'Review_Summary':review_summary,'Full_Review':full_review})
df

,Rating,Review_Summary,Full_Review
0,5,Classy product,Camera is awesome\nBest battery backup\nA perf...
1,5,Mind-blowing purchase,Photos super
2,5,Wonderful,This is amazing at all
3,5,Terrific,Very very good
4,5,Fabulous!,Super🔥 and good performance 👌❤️
...,...,...,...
95,5,Brilliant,Excellent Phone.
96,5,Terrific purchase,Value for money 🖤🖤
97,5,Fabulous!,It’s very good battery life and display and vi...
98,5,Awesome,I dreamt about this day from a long time.... G...
99,5,Wonderful,Very good

#### Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the
search field.
You have to scrape 3 attributes of each sneaker:
1. Brand
2. Product Description
3. Price
As shown in the below image, you have to scrape the above attributes.

In [48]:
#Opening the flipkart page on automated chrome driver
driver.get("https://www.flipkart.com/")

In [49]:
# entering sneakers in the search field

search=driver.find_element(By.CLASS_NAME,"_3704LK")
search.send_keys('sneakers')

In [50]:
#clicking the search button
search_btn=driver.find_element(By.CLASS_NAME, "L0Z3Pu")
search_btn.click()

In [51]:
# scraping sneakers data for brand, product price
brand=[]
product_desc=[]
price=[]

start=0
end=3    #to scrape data from the first 3 pages
for page in range(start,end):
    brand_name=driver.find_elements(By.XPATH, '//div[@class="_2WkVRV"]')
    for i in brand_name:
        brand.append(i.text)
        
    description=driver.find_elements(By.XPATH, '//a[@class="IRpwTa"]')
    for i in description:
        product_desc.append(i.text)
    
    prc=driver.find_elements(By.XPATH, '//div[@class="_30jeq3"]')
    for i in prc:
        price.append(i.text)
    next_button=driver.find_element(By.XPATH,'//a[@class="_1LKTO3"]')
    next_button.click()
    time.sleep(5)

In [52]:
print(len(brand),len(product_desc),len(price))

120 111 120

In [53]:
import pandas as pd
df=pd.DataFrame({'Brand':brand[0:100],'Product_Description':product_desc[0:100],'Price':price[0:100]})
df

        Brand                                Product_Description Price
0   BAUCHHAAR                                   Sneakers For Men  ₹474
1   BAUCHHAAR                                   Sneakers For Men  ₹473
2    Magnolia  Modern Trendy Sneakers boot Sneakers Sneakers ...  ₹499
3        aadi  Synthetic Leather |Lightweight|Comfort|Summer|...  ₹387
4      BRUTON               Modern Trendy Shoes Sneakers For Men  ₹299
..        ...                                                ...   ...
95     Kzaara                                   Sneakers For Men  ₹499
96   RapidBox                         Hustle V2 Sneakers For Men  ₹695
97      BIRDE                         Hustle V2 Sneakers For Men  ₹479
98      asian                     STREET ICON M Sneakers For Men  ₹499
99     BRUTON  Smooth Black Sports,Casual,Walking,Gym Sneaker...  ₹499

[100 rows x 3 columns]

#### Q7: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU Type filter to “Intel Core i7” as shown in the below image:
    
After setting the filters scrape first 10 laptops data. You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [54]:
#Opening the amazon page on automated chrome driver
driver.get("https://www.amazon.in/")

In [55]:
# entering laptop in the search field

search=driver.find_element(By.ID,"twotabsearchtextbox")
search.send_keys('Laptop')

In [56]:
#clicking the search button
search_btn=driver.find_element(By.ID, "nav-search-submit-button")
search_btn.click()

In [57]:
#clicking the CPU Type filter
CPU_Type=driver.find_element(By.XPATH, "/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[7]/span[10]/li/span/a/span")
CPU_Type.click()

In [58]:
# scraping laptop data for title, rating & price
title=[]
ratings=[]
price=[]


title_tags=driver.find_elements(By.XPATH, '//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in title_tags[0:10]:
    title.append(i.text)
        
rating_tags=driver.find_elements(By.XPATH, '//span[@class="a-icon-alt"]')
for i in rating_tags[0:10]:
    ratings.append(i.text)
    
price_tags=driver.find_elements(By.XPATH, '//span[@class="a-price-whole"]')
for i in price_tags[0:10]:
    price.append(i.text)

In [59]:
print(len(title),len(ratings),len(price))

10 10 10

In [60]:
import pandas as pd
df=pd.DataFrame({'Title':title,'Ratings':ratings,'Price':price})
df

                                               Title Ratings   Price
0  Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm...          23,399
1  ASUS [Smart Choice] Vivobook 15, Intel Celeron...          28,990
2  HP Laptop 15s, Intel Celeron N4500, 15.6 inch(...          30,490
3  Lenovo IdeaPad Slim 3 Chromebook Intel Celeron...          18,990
4  Lenovo IdeaPad 1 Intel Core Celeron N4020 14" ...          25,190
5  AXL Laptop (Vayu Book) Newly Launched Thin & L...          19,990
6  Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm...          23,390
7  AXL VayuBook Laptop 14.1 Inch FHD IPS Display ...          16,990
8  Walker Notebook/Laptop PC Model No - NU14A1, 1...          16,990
9  (Refurbished) Lenovo IdeaPad 3 Chromebook Inte...          16,141

#### Q8: Write a python program to scrape data for Top 1000 Quotes of All Time.
The above task will be done in following steps:
1. First get the webpage https://www.azquotes.com/
2. Click on Top Quotes
3. Then scrap a) Quote b) Author c) Type Of Quotes

In [63]:
#Opening the azquotes page on automated chrome driver
driver.get("https://www.azquotes.com/")

In [67]:
# Click on Top Quotes
top_quote=driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a")
top_quote.click()

In [68]:
# scraping quotes data
quote=[]
author=[]
quote_type=[]

start=0
end=10 #to scrape data from the first 10 pages
for page in range(start,end):
    quote_tags=driver.find_elements(By.XPATH, '//a[@class="title"]')
    for i in quote_tags:
        quote.append(i.text)
        
    author_tags=driver.find_elements(By.XPATH, '//div[@class="author"]')
    for i in author_tags:
        author.append(i.text)
    
    type_tags=driver.find_elements(By.XPATH, '//div[@class="tags"]')
    for i in type_tags:
        quote_type.append(i.text)
    next_button=driver.find_element(By.XPATH,"/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a")
    next_button.click()
    time.sleep(5)

In [69]:
print(len(quote),len(author),len(quote_type))

1000 1000 1000

In [70]:
import pandas as pd
df=pd.DataFrame({'Quote':quote,'Author':author,'Type_of_quote':quote_type})
df

,Quote,Author,Type_of_quote
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,Regret for the things we did can be tempered b...,Sydney J. Harris,"Love, Inspirational, Motivational"
996,America... just a nation of two hundred millio...,Hunter S. Thompson,"Gun, Two, Qualms About"
997,For every disciplined effort there is a multip...,Jim Rohn,"Inspirational, Greatness, Best Effort"
998,"The spiritual journey is individual, highly pe...",Ram Dass,"Spiritual, Truth, Yoga"
999,The mind is not a vessel to be filled but a fi...,Plutarch,"Inspirational, Leadership, Education"

#### Q9: Write a python program to display list of respected former Prime Ministers of India(i.e. Name, Born-Dead, Term of office, Remarks) from https://www.jagranjosh.com/.

This task will be done in following steps:
1. First get the webpagehttps://www.jagranjosh.com/
2. Then You have to click on the GK option
3. Then click on the List of all Prime Ministers of India
4. Then scrap the mentioned data and make theDataFrame.

In [76]:
#Opening the jagranjosh page on automated chrome driver
driver.get("https://www.jagranjosh.com/")

In [77]:
#clicking on GK
gk=driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/div/div[1]/div/div[5]/div/div[1]/header/div[3]/ul/li[3]/a")
gk.click()

In [78]:
#click on prime ministers
prime_ministers=driver.find_element(By.XPATH, "/html/body/div[1]/div/div/div[2]/div/div[10]/div/div/ul/li[2]/a")
prime_ministers.click()

In [79]:
#scrape prime ministers data
prime_ministers_data=[]
table = driver.find_elements(By.CLASS_NAME, "//*[@id='itemdiv']/div[4]/span/div[3]/table/tbody")
for row in table:
    columns = row.find_elements(By.TAG_NAME, 'td')
    for column in columns:
        name = columns[1].text.strip()
        born_dead = columns[2].text.strip()
        term_of_office = columns[3].text.strip()
        remarks = columns[4].text.strip()

    prime_ministers_data.append({
            'Name': name,
            'Born-Dead': born_dead,
            'Term of Office': term_of_office,
            'Remarks': remarks
        })

prime_ministers_data

InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=115.0.5790.99); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
Backtrace:
	GetHandleVerifier [0x011AA813+48355]
	(No symbol) [0x0113C4B1]
	(No symbol) [0x01045358]
	(No symbol) [0x010487A1]
	(No symbol) [0x010499E1]
	(No symbol) [0x01049A80]
	(No symbol) [0x0107061C]
	(No symbol) [0x01070B3B]
	(No symbol) [0x0109E26C]
	(No symbol) [0x0108A784]
	(No symbol) [0x0109C922]
	(No symbol) [0x0108A536]
	(No symbol) [0x010682DC]
	(No symbol) [0x010693DD]
	GetHandleVerifier [0x0140AABD+2539405]
	GetHandleVerifier [0x0144A78F+2800735]
	GetHandleVerifier [0x0144456C+2775612]
	GetHandleVerifier [0x012351E0+616112]
	(No symbol) [0x01145F8C]
	(No symbol) [0x01142328]
	(No symbol) [0x0114240B]
	(No symbol) [0x01134FF7]
	BaseThreadInitThunk [0x76897D59+25]
	RtlInitializeExceptionChain [0x7795B79B+107]
	RtlClearBits [0x7795B71F+191]

#### Q10: Write a python program to display list of 50 Most expensive cars in the world (i.e. Car name and Price) from https://www.motor1.com/
This task will be done in following steps:
1. First get the webpage https://www.motor1.com/
2. Then You have to type in the search bar ’50 most expensive cars’
3. Then click on 50 most expensive cars in the world..
4. Then scrap the mentioned data and make the dataframe.

In [80]:
#Opening the motor1 page on automated chrome driver
driver.get("https://www.motor1.com/")

In [81]:
# entering 50 most expensive cars in the search field

search=driver.find_element(By.ID,"search_input")
search.send_keys('50 most expensive cars')

In [82]:
#clicking the search button
search_btn=driver.find_element(By.XPATH, "/html/body/div[10]/div[2]/div/div/div[3]/div/div/div/form/button[1]")
search_btn.click()

In [83]:
article=driver.find_element(By.XPATH, "/html/body/div[10]/div[9]/div/div[1]/div/div/div[2]/div/div[1]/h3/a")
article.click()

In [84]:
car_name=[]
Price=[]

# scraping car name from web page
name_tags=driver.find_elements(By.XPATH, "//h3[@class='subheader']")
for i in name_tags:
    car_name.append(i.text)


# scraping price from web page
price_tags=driver.find_elements(By.XPATH, "//span[@class='ellipsis fleft locWdth']")
for i in location_tags[0:10]:
    location=i.text
    job_location3.append(location)

StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=115.0.5790.99); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
Backtrace:
	GetHandleVerifier [0x011AA813+48355]
	(No symbol) [0x0113C4B1]
	(No symbol) [0x01045358]
	(No symbol) [0x0104E5A3]
	(No symbol) [0x01048A78]
	(No symbol) [0x01047C03]
	(No symbol) [0x010499E1]
	(No symbol) [0x01049A80]
	(No symbol) [0x0106D2FD]
	(No symbol) [0x0108A73C]
	(No symbol) [0x01069A36]
	(No symbol) [0x0108AA94]
	(No symbol) [0x0109C922]
	(No symbol) [0x0108A536]
	(No symbol) [0x010682DC]
	(No symbol) [0x010693DD]
	GetHandleVerifier [0x0140AABD+2539405]
	GetHandleVerifier [0x0144A78F+2800735]
	GetHandleVerifier [0x0144456C+2775612]
	GetHandleVerifier [0x012351E0+616112]
	(No symbol) [0x01145F8C]
	(No symbol) [0x01142328]
	(No symbol) [0x0114240B]
	(No symbol) [0x01134FF7]
	BaseThreadInitThunk [0x76897D59+25]
	RtlInitializeExceptionChain [0x7795B79B+107]
	RtlClearBits [0x7795B71F+191]